blog/urls.py
from blog.views import IndexView, PostView, AddPostView, DeletePostView, EditPostView
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("posts", IndexView.as_view(), name="posts"),
    path("posts/new", AddPostView.as_view(), name="add_post"),
    path("posts/<int:pk>", PostView.as_view(), name="post"),
    path("posts/<int:pk>/edit", EditPostView.as_view(), name="edit_post"),
    path("posts/<int:pk>/delete", DeletePostView.as_view(), name="delete_post"),
]

clinic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls

from clinic.views import IndexView

app_name = "clinic"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path('', include('accounts.urls'), name="accounts"),
    path('admin/', admin.site.urls),
    path('panel/', include('panel.urls'), name="panel"),
    path('blog/', include('blog.urls'), name="blog"),
    path('email/', include(email_urls)),
    path('cart/', include('cart.urls'), name="cart"),
    path('chat/', include('chat.urls'), name="chat"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panel/urls.py
from django.urls import path, include
from panel.views import *

app_name = "panel"

urlpatterns = [
    path("", DashboardView.as_view(), name="index"),
    path("dashboard", DashboardView.as_view(), name="dashboard"),

    # Messaging URLs
    path("messaging", MessagingView.as_view(), name="messaging"),

    # Doctor URLs
    path("doctors/", DoctorsView.as_view(), name="doctors"),
    path("doctors/new", AddDoctorView.as_view(), name="add_doctor"),
    path("doctors/<int:pk>", DoctorView.as_view(), name="doctor"),
    path("doctors/<int:pk>/edit", EditDoctorView.as_view(), name="edit_doctor"),
    path("doctors/<int:pk>/delete", EditDoctorView.as_view(), name="delete_doctor"),

    # Patient URLs
    path("patients/", PatientsView.as_view(), name="patients"),
    path("patients/new", AddPatientView.as_view(), name="add_patient"),
    path("patients/<int:pk>", PatientView.as_view(), name="patient"),
    path("patients/<int:pk>/edit", EditPatientView.as_view(), name="edit_patient"),
    path("patients/<int:pk>/delete", DeletePatientView.as_view(), name="delete_patient"),

    # Product URLs
    path("products/", ProductsView.as_view(), name="products"),
    path("products/new", AddProductView.as_view(), name="add_product"),
    path("products/<int:pk>", ProductView.as_view(), name="product"),
    path("products/<int:pk>/edit", EditProductView.as_view(), name="edit_product"),
    path("products/<int:pk>/delete", DeleteProductView.as_view(), name="delete_product"),

    # Report URLs
    path("reports/", ReportsView.as_view(), name="reports"),
    path("reports/new", AddReportView.as_view(), name="add_report"),
    path("reports/<int:pk>", ReportView.as_view(), name="report"),
    path("reports/<int:pk>/edit", EditReportView.as_view(), name="edit_report"),
    path("reports/<int:pk>/delete", DeleteReportView.as_view(), name="delete_report"),

    # Appointment URLs
    path("appointments/", AppointmentsView.as_view(), name="appointments"),
    path("appointments/new", AddAppointmentView.as_view(), name="add_appointment"),
    path("appointments/<int:pk>/new", DoctorAddAppointmentView.as_view(), name="dr_add_appointment"),
    path("appointments/<int:pk>", AppointmentView.as_view(), name="appointment"),
    path("appointments/<int:pk>/edit", AppointmentView.as_view(), name="edit_appointment"),
    path("appointments/<int:pk>/delete", AppointmentView.as_view(), name="delete_appointment"),

    # Prescription URLs
    path("prescriptions/", PrescriptionsView.as_view(), name="prescriptions"),
    path("prescriptions/new", AddPrescriptionView.as_view(), name="add_prescription"),
    path("prescriptions/<int:pk>", PrescriptionView.as_view(), name="prescription"),
    path("prescriptions/int:pk>/edit", EditPrescriptionView.as_view(), name="edit_prescription"),
    path("prescriptions/<int:pk>/delete", DeletePrescriptionView.as_view(), name="delete_prescription"),

]

panel/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View
from clinic.settings import MODELS_PER_PAGE
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.utils import timezone
from django.utils.timezone import now
from panel.roles import Roles
from .models import Report, Appointment, Prescription, PrescriptionFile, Product, ProductImage, ReportFile
from .forms import PrescriptionForm, AddProductForm, AddAppointmentForm, DoctorAddAppointmentForm, ReportForm
from accounts.models import User

class PanelView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'redirect'


class DashboardView(PanelView):
    def get(self, request):
        context = {'current_page': 'home'}
        return render(request, 'panel/dashboard.html', context)


# Chat Views


class MessagingView(PanelView):
    def get(self, request):
        chats = []
        context = {'current_page': 'messaging', 'chats': chats}
        return render(request, 'panel/messaging.html', context)


# Prescription Views


class PrescriptionsView(PanelView):
    def get(self, request):
        prescriptions = Prescription.objects.all()
        paginator = Paginator(prescriptions, MODELS_PER_PAGE)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {'prescriptions': page_obj, 'current_page': 'prescriptions'}
        return render(request, 'prescription/prescriptions.html', context)


class PrescriptionView(PanelView):
    def get(self, request, pk):
        is_valid = False
        try:
            prescription = Prescription.objects.get(id=pk)
            is_valid = True
        except User.DoesNotExist:
            prescription = Prescription(doctor=None,
                                        patient=None,
                                        drugs=None,
                                        files=None,
                                        dateCreated=None,
                                        lastUpdated=None)
            is_valid = False  # Failsafe
        prescription.files = prescription.prescription_file_prescription.all()
        context = {'is_valid': is_valid, 'current_page': 'view_prescription', 'prescription': prescription}
        return render(request, 'prescription/prescription.html', context)


class AddPrescriptionView(PanelView):
    def get(self, request):
        form = PrescriptionForm()
        form.fields['patient'].queryset = User.objects.filter(role=Roles.PATIENT.value)
        form.fields['doctor'].queryset = User.objects.filter(role=Roles.DOCTOR.value)
        context = {'current_page': 'add_prescription', 'form': form}
        return render(request, 'prescription/add_prescription.html', context)

    def post(self, request):
        form = PrescriptionForm(request.POST, request.FILES)
        files = request.FILES.getlist('files')
        if form.is_valid():
            form.cleaned_data.pop('files')
            form.cleaned_data.pop('captcha')
            new_prescription = Prescription(**form.cleaned_data,
                                            dateCreated=now,
                                            lastUpdated=now)
            new_prescription.save()
            for f in files:
                file = PrescriptionFile(file=f, prescription=new_prescription)
                file.save()
            return redirect('')
        else:
            context = {"current_page": "add_prescription", "form": form}
            return render(request, "prescription/add_prescription.html", context)


class EditPrescriptionView(PanelView):
    def get(self, request, pk):

        prescription = Prescription.objects.get(id=pk)
        form = PrescriptionForm(instance=prescription)
        form.fields['patient'].queryset = User.objects.filter(role=Roles.PATIENT.value)
        form.fields['doctor'].queryset = User.objects.filter(role=Roles.DOCTOR.value)
        context = {'current_page': 'edit_prescription', 'form': form}
        return render(request, 'prescription/add_prescription.html', context)

    def post(self, request, pk):
        prescription = Prescription.objects.get(id=pk)
        form = PrescriptionForm(request.POST, request.FILES, instance=prescription)
        files = request.FILES.getlist('files')
        if form.is_valid():
            form.cleaned_data.pop('files')
            form.cleaned_data.pop('captcha')
            prescription.lastUpdated = now
            prescription.save()
            for f in files:
                file = PrescriptionFile(file=f, prescription=prescription)
                file.save()
            return redirect('panel:prescriptions')
        else:
            print(form.errors.as_data())
            return render(request, "prescription/add_prescription.html", {'form': form})


class DeletePrescriptionView(PanelView):
    def get(self, request, pk):
        context = {'current_page': 'delete_prescription'}
        return render(request, 'prescription/delete_prescription.html', context)

    def post(self, request, pk):
        if 'answer_no' in request.POST:
            return redirect('panel:prescription', pk)

        prescription = Prescription.objects.get(id=pk)
        prescription.delete()
        return redirect('panel:prescriptions')


# Report Views

class ReportView(PanelView):
    def get(self, request, pk):
        is_valid = False
        try:
            report = Report.objects.get(id=pk)
            is_valid = True
        except Report.DoesNotExist:
            report = Report(doctor=None,
                            patient=None,
                            files=None,
                            dateCreated=None,
                            lastUpdated=None)
            is_valid = False  # Failsafe
        report.files = report.report_file_report.all()
        context = {'is_valid': is_valid, 'current_page': 'view_report', 'report': report}
        return render(request, 'report/report.html', context)


class ReportsView(PanelView):
    def get(self, request):
        reports = Report.objects.all()
        paginator = Paginator(reports, MODELS_PER_PAGE)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {'current_page': 'reports', 'reports': page_obj}
        return render(request, 'report/reports.html', context)


class AddReportView(PanelView):
    def get(self, request):
        form = ReportForm()
        form.fields['patient'].queryset = User.objects.filter(role=Roles.PATIENT.value)
        form.fields['doctor'].queryset = User.objects.filter(role=Roles.DOCTOR.value)
        context = {"current_page": "add_report", "form": form}
        return render(request, 'report/add_report.html', context)

    def post(self, request):
        form = ReportForm(request.POST, request.FILES)
        files = request.FILES.getlist('files')

        if form.is_valid():
            form.cleaned_data.pop('files')
            form.cleaned_data.pop('captcha')
            new_report = Report(**form.cleaned_data,
                                dateCreated=now,
                                lastUpdated=now)
            new_report.save()
            for f in files:
                file = ReportFile(file=f, report=new_report)
                file.save()
            return redirect('panel:reports')
        else:
            context = {"current_page": "add_report", "form": form}
            return render(request, "report/add_report.html", context)


class EditReportView(PanelView):
    def get(self, request, pk):
        report = Report.objects.get(id=pk)
        form = ReportForm(instance=report)
        form.fields['patient'].queryset = User.objects.filter(role=Roles.PATIENT.value)
        form.fields['doctor'].queryset = User.objects.filter(role=Roles.DOCTOR.value)
        context = {'current_page': 'edit_report', 'form': form}
        return render(request, 'report/add_report.html', context)

    def post(self, request, pk):

        try:
            report = Report.objects.get(id=pk)
        except Report.DoesNotExist:
            context = {'current_page': 'edit_report', 'form': ReportForm()}
            messages.error(request, "Report not found")
            return render(request, "report/add_report.html", context)

        form = ReportForm(request.POST, request.FILES, instance=report)
        files = request.FILES.getlist('files')

        if form.is_valid():
            form.cleaned_data.pop('files')
            form.cleaned_data.pop('captcha')
            report.lastUpdated = now
            report.save()

            for f in files:
                file = ReportFile(file=f, report=report)
                file.save()
            return redirect('panel:reports')
        else:
            context = {'current_page': 'edit_report', 'form': form}
            return render(request, "report/add_report.html", context)


class DeleteReportView(PanelView):
    def get(self, request, pk):
        context = {'current_page': 'delete_report'}
        return render(request, 'report/delete_report.html', context)

    def post(self, request, pk):
        if 'answer_no' in request.POST:
            return redirect('panel:report', pk=pk)

        report = Report.objects.get(id=pk)
        report.delete()
        return redirect('panel:reports')


# Product Views



class ProductView(PanelView):
    def get(self, request, pk):
        try:
            product = Product.objects.get(id=pk)
            is_valid = True
        except Product.DoesNotExist:
            product = None
            is_valid = False

        product.images = product.product_image_product.all()
        context = {'product': product, 'current_page': 'view_product', 'is_valid': is_valid}
        return render(request, 'product/product.html', context)


class ProductsView(PanelView):
    def get(self, request):

panel/templates/prescription/add_prescription.html
{% extends 'panel/base/panel_base_index.html' %}


{% block content %}
    <div class="authentication-wrapper">
        <div class="container">
            <div class="row justify-content-center">
                    <div class="card col-md-8">
                        <form method="POST" action="" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.doctor.errors }}
                                <label for="{{ form.doctor.id_for_label }}">Doctor</label>
                                {{ form.doctor }}
                            </div>
                            <div class="form-group">
                                {{ form.patient.errors }}
                                <label for="{{ form.patient.id_for_label }}">Patient</label>
                                {{ form.patient }}
                            </div>
                            <div class="form-group">
                                {{ form.drugs.errors }}
                                <label for="{{ form.drugs.id_for_label }}">Drugs</label>
                                {{ form.drugs }}
                            </div>
                            <div class="form-group">
                                {{ form.files.errors }}
                                <label for="{{ form.files.id_for_label }}">Files</label>
                                {{ form.files }}
                            </div>
                            <div class="form-group">
                                {{ form.captcha.errors }}
                                <label for="{{ form.captcha.id_for_label }}">Captcha</label>
                                {{ form.captcha }}
                            </div>
                            <button class="btn btn-primary btn-block waves-effect waves-light" type="submit">Register</button>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

panel/templates/prescription/delete_prescription.html
{% extends 'panel/base/panel_base_index.html' %}

{% block title %}
<title>Delete Prescription - Clinicare</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="confirmation-card shadow">
            <form method="POST">
                {% csrf_token %}
                <h3>Are you sure?</h3>
                <p>Do you really want to delete this prescription?</p>
                <button type="submit" name="answer_yes" class="btn btn-primary">Yes</button>
                <button type="submit" name="answer_no" class="btn btn-secondary">No</button>
            </form>
        </div>
    </div>
{% endblock %}

panel/templates/prescription/prescription.html
{% extends 'panel/base/panel_base_index.html' %}

{% block title %}
<title>Prescription - Clinicare</title>
{% endblock %}

{% block content %}
    <div class="content-container container-fluid">
        <nav class="mt-3" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'panel:index' %}">Control Panel</a>
                <li class="breadcrumb-item"><a href="{% url 'panel:prescriptions' %}">Prescriptions</a></li>
                <li class="breadcrumb-item active" aria-current="page">Prescription #{{ prescription.id }}</li>
            </ol>
        </nav>
        <div class="button-row row shadow justify-content-end align-middle">
            <div class="btn-group" role="group" aria-label="Basic example">
                <a href="{% url 'panel:edit_prescription' pk=prescription.id %}">
                    <button type="button" class="border-left btn btn-outline btn-circle btn-lg">
                        <i class="fa fa-pencil"></i>
                    </button>
                </a>
                <a href="{% url 'panel:delete_prescription' pk=prescription.id %}">
                    <button type="button" class="border-left btn btn-outline btn-circle btn-lg">
                        <i class="fa fa-trash"></i>
                    </button>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-3 no-padding">
                <div class="card photo-card">
                    <div class="card-img">
                        {% load static %}
                        <img class="img-fluid" src="{% static 'avatar.png' %}">
                    </div>
                </div>
            </div>
            <div class="col card-before">
                <div class="card">
                    <div class="card-contents">
                        {% if is_valid == False %}
                            <h3 class="card-title" style="padding:0.5em">Prescription Not Found</h3>
                        {% endif %}
                            <div class="row">
                                <p class="col-sm-5">Doctor:</p>
                                <p class="col-sm-5">
                                    <a href="{% url 'panel:doctor' pk=prescription.doctor.id %}">{{ prescription.doctor }}</a>
                                </p>
                            </div>
                            <div class="row">
                                <p class="col-sm-5">Patient:</p>
                                <p class="col-sm-5">
                                    <a href="{% url 'panel:patient' pk=prescription.patient.id %}">{{ prescription.patient }}</a>
                                </p>
                            </div>
                            <div class="row">
                                <p class="col-sm-5">Drugs:</p>
                                <p class="col-sm-5">{{ prescription.drugs }}</p>
                            </div>
                            <div class="row">
                                <p class="col-sm-5">Files:</p>

                                <div class="col-sm-5">
                                    <div class="row">
                                        {% for attachment in prescription.files %}
                                            <div class="col-sm-3">
                                                <a href="{{ attachment.file.url }}" target="_blank">
                                                    <div class="embed-responsive embed-responsive-1by1 text-center">
                                                        {% load static %}
                                                        <img style="max-height: 100px; max-width: 100px;" class="embed-responsive-item" src="{% static 'attachment.png' %}">
                                                        <span class="text-white">File {{ attachment.id }}</span>
                                                    </div>
                                                </a>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <p class="col-sm-5">Last Updated:</p>
                                <p class="col-sm-5">{{ prescription.lastUpdated }}</p>
                            </div>
                            <div class="row">
                                <p class="col-sm-5">Prescription Created:</p>
                                <p class="col-sm-5">{{ prescription.dateCreated }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">

        </div>
    </div>
{% endblock %}

panel/templates/prescription/prescriptions.html
{% extends 'panel/base/panel_base_index.html' %}

{% block title %}
<title>Prescriptions - Clinicare</title>
{% endblock %}


{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <section class="container-header">
                <h2>Prescriptions</h2>
            </section>
            <nav class="mt-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'panel:index' %}">Control Panel</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Prescriptions</li>
                </ol>
            </nav>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Prescription List</h3>
                            <div class="card-tools">
                                <button class="btn btn-primary" data-toggle="collapse" href="#filter">
                                    <i class="fa fa-filter"></i> Filter
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Doctor</th>
                                        <th scope="col">Patient</th>
                                        <th scope="col">Date</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for prescription in prescriptions %}
                                    <tr>
                                        <th scope="row">{{ prescription.id }}</th>
                                        <td>
                                            <a href="{% url 'panel:doctor' pk=prescription.doctor.id %}">{{ prescription.doctor.first_name }} {{ prescription.doctor.last_name }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'panel:patient' pk=prescription.patient.id %}">{{ prescription.patient.first_name }} {{ prescription.patient.last_name }}</a>
                                        </td>
                                        <td>{{ prescription.dateCreated }}</td>
                                        <td>
                                            <a href="{% url 'panel:prescription' pk=prescription.id%}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="View">
                                                <i class="fa fa-eye ambitious-padding-btn"></i>
                                            </a>
                                            <a href="{% url 'panel:edit_prescription' pk=prescription.id %}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="Edit">
                                                <i class="fa fa-pencil ambitious-padding-btn"></i>
                                            </a>
                                            <a href="{% url 'panel:delete_prescription' pk=prescription.id %}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="Delete">
                                                <i class="fa fa-trash ambitious-padding-btn"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>


              <ul class="pagination">
                {% if prescriptions.has_previous %}
                  <li class="page-item"><a class="page-link" href="?page={{ prescriptions.previous_page_number }}">&laquo;</a></li>
                {% else %}
                  <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
                {% endif %}
                {% for i in prescriptions.paginator.page_range %}
                  {% if prescriptions.number == i %}
                    <li class="page-item active"><a class="page-link">{{ i }} <span class="sr-only">(current)</span></a></li>
                  {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if prescriptions.has_next %}
                  <li class="page-item"><a class="page-link" href="?page={{ prescriptions.next_page_number }}">&raquo;</a></li>
                {% else %}
                  <li class="page-item disabled"><a class="page-link">&raquo;</a></li>
                {% endif %}
              </ul>


        </div>
    </div>
{% endblock %}