accounts/urls.py
from django.urls import path

from .views import LoginView, RegisterView, LogoutView, ActivateView

app_name = "accounts"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("activate/", ActivateView.as_view(), name="activate"),
]

blog/urls.py
from blog.views import IndexView, PostView, AddPostView, DeletePostView, EditPostView
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("posts", IndexView.as_view(), name="posts"),
    path("posts/new", AddPostView.as_view(), name="add_post"),
    path("posts/<int:pk>", PostView.as_view(), name="post"),
    path("posts/<int:pk>/edit", EditPostView.as_view(), name="edit_post"),
    path("posts/<int:pk>/delete", DeletePostView.as_view(), name="delete_post"),
]

cart/urls.py
from cart.views import ShoppingCartView
from django.urls import path

app_name = "cart"

urlpatterns = [
    path("", ShoppingCartView.as_view(), name="cart"),
]

clinic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls

from clinic.views import IndexView

app_name = "clinic"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path('', include('accounts.urls'), name="accounts"),
    path('admin/', admin.site.urls),
    path('panel/', include('panel.urls'), name="panel"),
    path('blog/', include('blog.urls'), name="blog"),
    path('email/', include(email_urls)),
    path('cart/', include('cart.urls'), name="cart"),
    path('chat/', include('chat.urls'), name="chat"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panel/urls.py
from django.urls import path, include
from panel.views import *

app_name = "panel"

urlpatterns = [
    path("", DashboardView.as_view(), name="index"),
    path("dashboard", DashboardView.as_view(), name="dashboard"),

    # Messaging URLs
    path("messaging", MessagingView.as_view(), name="messaging"),

    # Doctor URLs
    path("doctors/", DoctorsView.as_view(), name="doctors"),
    path("doctors/new", AddDoctorView.as_view(), name="add_doctor"),
    path("doctors/<int:pk>", DoctorView.as_view(), name="doctor"),
    path("doctors/<int:pk>/edit", EditDoctorView.as_view(), name="edit_doctor"),
    path("doctors/<int:pk>/delete", EditDoctorView.as_view(), name="delete_doctor"),

    # Patient URLs
    path("patients/", PatientsView.as_view(), name="patients"),
    path("patients/new", AddPatientView.as_view(), name="add_patient"),
    path("patients/<int:pk>", PatientView.as_view(), name="patient"),
    path("patients/<int:pk>/edit", EditPatientView.as_view(), name="edit_patient"),
    path("patients/<int:pk>/delete", DeletePatientView.as_view(), name="delete_patient"),

    # Product URLs
    path("products/", ProductsView.as_view(), name="products"),
    path("products/new", AddProductView.as_view(), name="add_product"),
    path("products/<int:pk>", ProductView.as_view(), name="product"),
    path("products/<int:pk>/edit", EditProductView.as_view(), name="edit_product"),
    path("products/<int:pk>/delete", DeleteProductView.as_view(), name="delete_product"),

    # Report URLs
    path("reports/", ReportsView.as_view(), name="reports"),
    path("reports/new", AddReportView.as_view(), name="add_report"),
    path("reports/<int:pk>", ReportView.as_view(), name="report"),
    path("reports/<int:pk>/edit", EditReportView.as_view(), name="edit_report"),
    path("reports/<int:pk>/delete", DeleteReportView.as_view(), name="delete_report"),

    # Appointment URLs
    path("appointments/", AppointmentsView.as_view(), name="appointments"),
    path("appointments/new", AddAppointmentView.as_view(), name="add_appointment"),
    path("appointments/<int:pk>/new", DoctorAddAppointmentView.as_view(), name="dr_add_appointment"),
    path("appointments/<int:pk>", AppointmentView.as_view(), name="appointment"),
    path("appointments/<int:pk>/edit", AppointmentView.as_view(), name="edit_appointment"),
    path("appointments/<int:pk>/delete", AppointmentView.as_view(), name="delete_appointment"),

    # Prescription URLs
    path("prescriptions/", PrescriptionsView.as_view(), name="prescriptions"),
    path("prescriptions/new", AddPrescriptionView.as_view(), name="add_prescription"),
    path("prescriptions/<int:pk>", PrescriptionView.as_view(), name="prescription"),
    path("prescriptions/int:pk>/edit", EditPrescriptionView.as_view(), name="edit_prescription"),
    path("prescriptions/<int:pk>/delete", DeletePrescriptionView.as_view(), name="delete_prescription"),

]

panel/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View
from clinic.settings import MODELS_PER_PAGE
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.utils import timezone
from django.utils.timezone import now
from panel.roles import Roles
from .models import Report, Appointment, Prescription, PrescriptionFile, Product, ProductImage, ReportFile
from .forms import PrescriptionForm, AddProductForm, AddAppointmentForm, DoctorAddAppointmentForm, ReportForm
from accounts.models import User

class PanelView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'redirect'


class DashboardView(PanelView):
    def get(self, request):
        context = {'current_page': 'home'}
        return render(request, 'panel/dashboard.html', context)


# Chat Views


class MessagingView(PanelView):
    def get(self, request):
        chats = []
        context = {'current_page': 'messaging', 'chats': chats}
        return render(request, 'panel/messaging.html', context)


# Prescription Views


class PrescriptionsView(PanelView):
    def get(self, request):
        prescriptions = Prescription.objects.all()
        paginator = Paginator(prescriptions, MODELS_PER_PAGE)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {'prescriptions': page_obj, 'current_page': 'prescriptions'}
        return render(request, 'prescription/prescriptions.html', context)


class PrescriptionView(PanelView):
    def get(self, request, pk):
        is_valid = False
        try:
            prescription = Prescription.objects.get(id=pk)
            is_valid = True
        except User.DoesNotExist:
            prescription = Prescription(doctor=None,
                                        patient=None,
                                        drugs=None,
                                        files=None,
                                        dateCreated=None,
                                        lastUpdated=None)
            is_valid = False  # Failsafe
        prescription.files = prescription.prescription_file_prescription.all()
        context = {'is_valid': is_valid, 'current_page': 'view_prescription', 'prescription': prescription}
        return render(request, 'prescription/prescription.html', context)


class AddPrescriptionView(PanelView):
    def get(self, request):
        form = PrescriptionForm()
        form.fields['patient'].queryset = User.objects.filter(role=Roles.PATIENT.value)
        form.fields['doctor'].queryset = User.objects.filter(role=Roles.DOCTOR.value)
        context = {'current_page': 'add_prescription', 'form': form}
        return render(request, 'prescription/add_prescription.html', context)

    def post(self, request):
        form = PrescriptionForm(request.POST, request.FILES)
        files = request.FILES.getlist('files')
        if form.is_valid():
            form.cleaned_data.pop('files')
            form.cleaned_data.pop('captcha')
            new_prescription = Prescription(**form.cleaned_data,
                                            dateCreated=now,
                                            lastUpdated=now)
            new_prescription.save()
            for f in files:
                file = PrescriptionFile(file=f, prescription=new_prescription)
                file.save()
            return redirect('')
        else:
            context = {"current_page": "add_prescription", "form": form}
            return render(request, "prescription/add_prescription.html", context)


class EditPrescriptionView(PanelView):
    def get(self, request, pk):

        prescription = Prescription.objects.get(id=pk)
        form = PrescriptionForm(instance=prescription)
        form.fields['patient'].queryset = User.objects.filter(role=Roles.PATIENT.value)
        form.fields['doctor'].queryset = User.objects.filter(role=Roles.DOCTOR.value)
        context = {'current_page': 'edit_prescription', 'form': form}
        return render(request, 'prescription/add_prescription.html', context)

    def post(self, request, pk):
        prescription = Prescription.objects.get(id=pk)
        form = PrescriptionForm(request.POST, request.FILES, instance=prescription)
        files = request.FILES.getlist('files')
        if form.is_valid():
            form.cleaned_data.pop('files')
            form.cleaned_data.pop('captcha')
            prescription.lastUpdated = now
            prescription.save()
            for f in files:
                file = PrescriptionFile(file=f, prescription=prescription)
                file.save()
            return redirect('panel:prescriptions')
        else:
            print(form.errors.as_data())
            return render(request, "prescription/add_prescription.html", {'form': form})


class DeletePrescriptionView(PanelView):
    def get(self, request, pk):
        context = {'current_page': 'delete_prescription'}
        return render(request, 'prescription/delete_prescription.html', context)

    def post(self, request, pk):
        if 'answer_no' in request.POST:
            return redirect('panel:prescription', pk)

        prescription = Prescription.objects.get(id=pk)
        prescription.delete()
        return redirect('panel:prescriptions')


# Report Views

class ReportView(PanelView):
    def get(self, request, pk):
        is_valid = False
        try:
            report = Report.objects.get(id=pk)
            is_valid = True
        except Report.DoesNotExist:
            report = Report(doctor=None,
                            patient=None,
                            files=None,
                            dateCreated=None,
                            lastUpdated=None)
            is_valid = False  # Failsafe
        report.files = report.report_file_report.all()
        context = {'is_valid': is_valid, 'current_page': 'view_report', 'report': report}
        return render(request, 'report/report.html', context)


class ReportsView(PanelView):
    def get(self, request):
        reports = Report.objects.all()
        paginator = Paginator(reports, MODELS_PER_PAGE)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {'current_page': 'reports', 'reports': page_obj}
        return render(request, 'report/reports.html', context)


class AddReportView(PanelView):
    def get(self, request):
        form = ReportForm()
        form.fields['patient'].queryset = User.objects.filter(role=Roles.PATIENT.value)
        form.fields['doctor'].queryset = User.objects.filter(role=Roles.DOCTOR.value)
        context = {"current_page": "add_report", "form": form}
        return render(request, 'report/add_report.html', context)

    def post(self, request):
        form = ReportForm(request.POST, request.FILES)
        files = request.FILES.getlist('files')

        if form.is_valid():
            form.cleaned_data.pop('files')
            form.cleaned_data.pop('captcha')
            new_report = Report(**form.cleaned_data,
                                dateCreated=now,
                                lastUpdated=now)
            new_report.save()
            for f in files:
                file = ReportFile(file=f, report=new_report)
                file.save()
            return redirect('panel:reports')
        else:
            context = {"current_page": "add_report", "form": form}
            return render(request, "report/add_report.html", context)


class EditReportView(PanelView):
    def get(self, request, pk):
        report = Report.objects.get(id=pk)
        form = ReportForm(instance=report)
        form.fields['patient'].queryset = User.objects.filter(role=Roles.PATIENT.value)
        form.fields['doctor'].queryset = User.objects.filter(role=Roles.DOCTOR.value)
        context = {'current_page': 'edit_report', 'form': form}
        return render(request, 'report/add_report.html', context)

    def post(self, request, pk):

        try:
            report = Report.objects.get(id=pk)
        except Report.DoesNotExist:
            context = {'current_page': 'edit_report', 'form': ReportForm()}
            messages.error(request, "Report not found")
            return render(request, "report/add_report.html", context)

        form = ReportForm(request.POST, request.FILES, instance=report)
        files = request.FILES.getlist('files')

        if form.is_valid():
            form.cleaned_data.pop('files')
            form.cleaned_data.pop('captcha')
            report.lastUpdated = now
            report.save()

            for f in files:
                file = ReportFile(file=f, report=report)
                file.save()
            return redirect('panel:reports')
        else:
            context = {'current_page': 'edit_report', 'form': form}
            return render(request, "report/add_report.html", context)


class DeleteReportView(PanelView):
    def get(self, request, pk):
        context = {'current_page': 'delete_report'}
        return render(request, 'report/delete_report.html', context)

    def post(self, request, pk):
        if 'answer_no' in request.POST:
            return redirect('panel:report', pk=pk)

        report = Report.objects.get(id=pk)
        report.delete()
        return redirect('panel:reports')


# Product Views



class ProductView(PanelView):
    def get(self, request, pk):
        try:
            product = Product.objects.get(id=pk)
            is_valid = True
        except Product.DoesNotExist:
            product = None
            is_valid = False

        product.images = product.product_image_product.all()
        context = {'product': product, 'current_page': 'view_product', 'is_valid': is_valid}
        return render(request, 'product/product.html', context)


class ProductsView(PanelView):
    def get(self, request):

panel/templates/panel/base/panel_base_content.html
{% block content %}
    <h3>404 Not Found</h3>
    <p>The page you requested is not found.</p>
{% endblock %}

panel/templates/panel/base/panel_base_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}<title>Clinic Template</title>{% endblock %}

    {%  load static %}
    <link href="{% static 'base/css/bootstrap-4.4.1.css' %}" rel="stylesheet">
	<link href="{% static 'panel/css/styles.css' %}" rel="stylesheet">
	<link href="{% static 'base/fontawesome/css/all.css' %}" rel="stylesheet">
    {% block extracss %}{% endblock %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

  </head>
  <body>
	<div class="wrapper">
        {% block sidebar %}
            {% include "panel/base/panel_sidebar.html" %}
        {% endblock %}

        <div class="right-wrapper">
            {% block navbar %}
                {% include 'panel/base/panel_navbar.html' %}
            {% endblock %}

            {% block content %}
                {% include 'panel/base/panel_base_content.html' %}
            {% endblock %}
        </div>
	</div>
    <script src="{% static 'base/js/jquery-3.4.1.min.js' %}"></script>
    {% block extrajs %}{% endblock %}
    <script src="{% static 'base/js/popper.min.js' %}"></script>
    <script src="{% static 'base/js/bootstrap-4.4.1.js' %}"></script>
  </body>
</html>

panel/templates/panel/base/panel_navbar.html
<nav class="navbar navbar-expand navbar-light bg-light">
    <a class="navbar-brand" href="{% url "index"%}">
        {% load static %}
        <img src="{% static 'favicon.ico' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Clinicare
    </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'panel:index' %}">Control Panel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
                <li class="nav-item nav-right">
                    <a href="{% url 'cart:cart' %}">Shopping Cart</a>
                    <i class="fa fa-shopping-cart"></i>
                </li>
                <li class="nav-item">
                    <div class="dropdown profile-dropdown">
                        <a class="no-transition no-hover" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span>Hello, {{ request.user.first_name }}</span>
                            <img class="rounded img-fluid ml-2 mr-2" style="max-width: 50px; max-height: 50px" src="{{ request.user.photo.url }}"></img>
                            <i class="fa fa-angle-down"></i>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
{#                                <a class="dropdown-item" href="#">Edit Profile</a>#}
{#                                <a class="dropdown-item" href="#">Settings</a>#}
{#                                <a class="dropdown-item" href="#">Help & Support</a>#}
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                            </div>
                        </a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'accounts:login' %}" class="mr-2">Login</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'accounts:register' %}" class="mr-2">Register</a>
                </li>
            {% endif %}
        </ul>
{#            <form class="form-inline my-2 my-lg-0">#}
{#              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
{#              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
{#            </form>#}

    </div>
</nav>

panel/templates/panel/base/panel_sidebar.html
<nav id="sidebar">
			<div class="container">
				<div class="row">
					<div class="col-9 sidebar-header">
				 		<h3>Clinicare</h3>
					</div>
					<div class="col sidebar-header sidebar-toggle">
						<i class="fa-solid fa-chevron-left"></i>
					</div>
				</div>
			</div>
	<ul class="list-unstyled components">
		<p>Welcome back, {{ request.user.first_name }}!</p>
{#        <img class="img-fluid ml-1 mb" src="{{ request.user.photo.url }}" style="max-width: 40px; max-height: 40px;">#}
		<li class="{% if current_page == "home" %} active {% endif %}">

			<a href="{%url 'panel:dashboard'%}"><i class="fa-solid fa-gauge"></i>Dashboard</a>
		</li>
		<li class="{% if current_page == "messaging" %} active {% endif %}">

			<a href="{%url 'panel:messaging'%}"><i class="fa fa-message"></i>Messages</a>
		</li>
		<li class="{% if current_page == "doctors" or current_page == "view_doctor" or current_page == "add_doctor" or current_page == "edit_doctor" %} active {% endif %}">
			<a href="#doctorsSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa-solid fa-user-doctor"></i>Doctors</a>
			<ul class="collapse list-unstyled" id="doctorsSubmenu">
				<li>
					<a href="{% url 'panel:doctors' %}">Doctors List</a>
				</li>
				<li>
					<a href="{% url 'panel:add_doctor' %}">Add a New Doctor</a>
				</li>
			</ul>
		</li>
		<li class="{% if current_page == "prescriptions" or current_page == "view_prescription" or current_page == "add_prescription" or current_page == "edit_prescription" %} active {% endif %}">
			<a href="#prescriptionsSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa-solid fa-prescription-bottle"></i>Prescriptions</a>
			<ul class="collapse list-unstyled" id="prescriptionsSubmenu">
				<li>
					<a href="{% url 'panel:prescriptions' %}">Prescriptions List</a>
				</li>
				<li>
					<a href="{% url 'panel:add_prescription' %}">Add a New Prescription</a>
				</li>
			</ul>
		</li>
		<li class="{% if current_page == "reports" or current_page == "view_report" or current_page == "add_report" or current_page == "edit_report" %} active {% endif %}">
			<a href="#reportsSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa-solid fa-flask"></i>Reports</a>
			<ul class="collapse list-unstyled" id="reportsSubmenu">
				<li>
					<a href="{% url 'panel:reports' %}">Reports List</a>
				</li>
				<li>
					<a href="{% url 'panel:add_report' %}">Add a New Report</a>
				</li>
			</ul>
		</li>
		<li class="{% if current_page == "patients" or current_page == "view_patient" or current_page == "add_patient" or current_page == "edit_patient" %} active {% endif %}">

			<a href="#patientsSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa-solid fa-bed"></i>Patients</a>
			<ul class="collapse list-unstyled" id="patientsSubmenu">
				<li>
					<a href="{% url 'panel:patients' %}">Patients List</a>
				</li>
				<li>
					<a href="{% url 'panel:add_patient' %}">Add a New Patient</a>
				</li>
			</ul>
		</li>
		<li class="{% if current_page == "products" or current_page == "view_product" or current_page == "add_product" or current_page == "edit_product" %} active {% endif %}">
			<a href="#productsSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa-solid fa-shop"></i>Products</a>
			<ul class="collapse list-unstyled" id="productsSubmenu">
				<li>
					<a href="{% url 'panel:products' %}">Products List</a>
				</li>
				<li>
					<a href="{% url 'panel:add_product' %}">Add a New Product</a>
				</li>
				<li>
					<a href="#">My Purchases</a>
				</li>
			</ul>
		</li>
		<li class="{% if current_page == "appointments" or current_page == "view_appointment" or current_page == "add_appointment" or current_page == "edit_appointment" %} active {% endif %}">
			<a href="#appointmentsSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa-solid fa-calendar-check"></i>Appointments</a>
			<ul class="collapse list-unstyled" id="appointmentsSubmenu">
				<li>
					<a href="{% url 'panel:appointments' %}">Appointment List</a>
				</li>
				<li>
					<a href="{% url 'panel:add_appointment' %}">Book a New Appointment</a>
				</li>
			</ul>
		</li>
		<li>
			<a href="#postsSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa-solid fa-comment"></i>Blog Posts</a>
			<ul class="collapse list-unstyled" id="postsSubmenu">
				<li>
					<a href="{% url 'blog:posts' %}">Post List</a>
				</li>
				<li>
					<a href="{% url 'blog:add_post' %}">New Post</a>
				</li>
			</ul>
		</li>
	</ul>
</nav>