blog/urls.py
from blog.views import IndexView, PostView, AddPostView, DeletePostView, EditPostView
from django.urls import path

app_name = "blog"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("posts", IndexView.as_view(), name="posts"),
    path("posts/new", AddPostView.as_view(), name="add_post"),
    path("posts/<int:pk>", PostView.as_view(), name="post"),
    path("posts/<int:pk>/edit", EditPostView.as_view(), name="edit_post"),
    path("posts/<int:pk>/delete", DeletePostView.as_view(), name="delete_post"),
]

clinic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls

from clinic.views import IndexView

app_name = "clinic"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path('', include('accounts.urls'), name="accounts"),
    path('admin/', admin.site.urls),
    path('panel/', include('panel.urls'), name="panel"),
    path('blog/', include('blog.urls'), name="blog"),
    path('email/', include(email_urls)),
    path('cart/', include('cart.urls'), name="cart"),
    path('chat/', include('chat.urls'), name="chat"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panel/urls.py
from django.urls import path, include
from panel.views import *

app_name = "panel"

urlpatterns = [
    path("", DashboardView.as_view(), name="index"),
    path("dashboard", DashboardView.as_view(), name="dashboard"),

    # Messaging URLs
    path("messaging", MessagingView.as_view(), name="messaging"),

    # Doctor URLs
    path("doctors/", DoctorsView.as_view(), name="doctors"),
    path("doctors/new", AddDoctorView.as_view(), name="add_doctor"),
    path("doctors/<int:pk>", DoctorView.as_view(), name="doctor"),
    path("doctors/<int:pk>/edit", EditDoctorView.as_view(), name="edit_doctor"),
    path("doctors/<int:pk>/delete", EditDoctorView.as_view(), name="delete_doctor"),

    # Patient URLs
    path("patients/", PatientsView.as_view(), name="patients"),
    path("patients/new", AddPatientView.as_view(), name="add_patient"),
    path("patients/<int:pk>", PatientView.as_view(), name="patient"),
    path("patients/<int:pk>/edit", EditPatientView.as_view(), name="edit_patient"),
    path("patients/<int:pk>/delete", DeletePatientView.as_view(), name="delete_patient"),

    # Product URLs
    path("products/", ProductsView.as_view(), name="products"),
    path("products/new", AddProductView.as_view(), name="add_product"),
    path("products/<int:pk>", ProductView.as_view(), name="product"),
    path("products/<int:pk>/edit", EditProductView.as_view(), name="edit_product"),
    path("products/<int:pk>/delete", DeleteProductView.as_view(), name="delete_product"),

    # Report URLs
    path("reports/", ReportsView.as_view(), name="reports"),
    path("reports/new", AddReportView.as_view(), name="add_report"),
    path("reports/<int:pk>", ReportView.as_view(), name="report"),
    path("reports/<int:pk>/edit", EditReportView.as_view(), name="edit_report"),
    path("reports/<int:pk>/delete", DeleteReportView.as_view(), name="delete_report"),

    # Appointment URLs
    path("appointments/", AppointmentsView.as_view(), name="appointments"),
    path("appointments/new", AddAppointmentView.as_view(), name="add_appointment"),
    path("appointments/<int:pk>/new", DoctorAddAppointmentView.as_view(), name="dr_add_appointment"),
    path("appointments/<int:pk>", AppointmentView.as_view(), name="appointment"),
    path("appointments/<int:pk>/edit", AppointmentView.as_view(), name="edit_appointment"),
    path("appointments/<int:pk>/delete", AppointmentView.as_view(), name="delete_appointment"),

    # Prescription URLs
    path("prescriptions/", PrescriptionsView.as_view(), name="prescriptions"),
    path("prescriptions/new", AddPrescriptionView.as_view(), name="add_prescription"),
    path("prescriptions/<int:pk>", PrescriptionView.as_view(), name="prescription"),
    path("prescriptions/int:pk>/edit", EditPrescriptionView.as_view(), name="edit_prescription"),
    path("prescriptions/<int:pk>/delete", DeletePrescriptionView.as_view(), name="delete_prescription"),

]

panel/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View
from clinic.settings import MODELS_PER_PAGE
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.utils import timezone
from django.utils.timezone import now
from panel.roles import Roles
from .models import Report, Appointment, Prescription, PrescriptionFile, Product, ProductImage, ReportFile
from .forms import PrescriptionForm, AddProductForm, AddAppointmentForm, DoctorAddAppointmentForm, ReportForm
from accounts.models import User

class PanelView(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'redirect'


class DashboardView(PanelView):
    def get(self, request):
        context = {'current_page': 'home'}
        return render(request, 'panel/dashboard.html', context)


# Chat Views


class MessagingView(PanelView):
    def get(self, request):
        chats = []
        context = {'current_page': 'messaging', 'chats': chats}
        return render(request, 'panel/messaging.html', context)


# Prescription Views


class PrescriptionsView(PanelView):
    def get(self, request):
        prescriptions = Prescription.objects.all()
        paginator = Paginator(prescriptions, MODELS_PER_PAGE)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {'prescriptions': page_obj, 'current_page': 'prescriptions'}
        return render(request, 'prescription/prescriptions.html', context)


class PrescriptionView(PanelView):
    def get(self, request, pk):
        is_valid = False
        try:
            prescription = Prescription.objects.get(id=pk)
            is_valid = True
        except User.DoesNotExist:
            prescription = Prescription(doctor=None,
                                        patient=None,
                                        drugs=None,
                                        files=None,
                                        dateCreated=None,
                                        lastUpdated=None)
            is_valid = False  # Failsafe
        prescription.files = prescription.prescription_file_prescription.all()
        context = {'is_valid': is_valid, 'current_page': 'view_prescription', 'prescription': prescription}
        return render(request, 'prescription/prescription.html', context)


class AddPrescriptionView(PanelView):
    def get(self, request):
        form = PrescriptionForm()
        form.fields['patient'].queryset = User.objects.filter(role=Roles.PATIENT.value)
        form.fields['doctor'].queryset = User.objects.filter(role=Roles.DOCTOR.value)
        context = {'current_page': 'add_prescription', 'form': form}
        return render(request, 'prescription/add_prescription.html', context)

    def post(self, request):
        form = PrescriptionForm(request.POST, request.FILES)
        files = request.FILES.getlist('files')
        if form.is_valid():
            form.cleaned_data.pop('files')
            form.cleaned_data.pop('captcha')
            new_prescription = Prescription(**form.cleaned_data,
                                            dateCreated=now,
                                            lastUpdated=now)
            new_prescription.save()
            for f in files:
                file = PrescriptionFile(file=f, prescription=new_prescription)
                file.save()
            return redirect('')
        else:
            context = {"current_page": "add_prescription", "form": form}
            return render(request, "prescription/add_prescription.html", context)


class EditPrescriptionView(PanelView):
    def get(self, request, pk):

        prescription = Prescription.objects.get(id=pk)
        form = PrescriptionForm(instance=prescription)
        form.fields['patient'].queryset = User.objects.filter(role=Roles.PATIENT.value)
        form.fields['doctor'].queryset = User.objects.filter(role=Roles.DOCTOR.value)
        context = {'current_page': 'edit_prescription', 'form': form}
        return render(request, 'prescription/add_prescription.html', context)

    def post(self, request, pk):
        prescription = Prescription.objects.get(id=pk)
        form = PrescriptionForm(request.POST, request.FILES, instance=prescription)
        files = request.FILES.getlist('files')
        if form.is_valid():
            form.cleaned_data.pop('files')
            form.cleaned_data.pop('captcha')
            prescription.lastUpdated = now
            prescription.save()
            for f in files:
                file = PrescriptionFile(file=f, prescription=prescription)
                file.save()
            return redirect('panel:prescriptions')
        else:
            print(form.errors.as_data())
            return render(request, "prescription/add_prescription.html", {'form': form})


class DeletePrescriptionView(PanelView):
    def get(self, request, pk):
        context = {'current_page': 'delete_prescription'}
        return render(request, 'prescription/delete_prescription.html', context)

    def post(self, request, pk):
        if 'answer_no' in request.POST:
            return redirect('panel:prescription', pk)

        prescription = Prescription.objects.get(id=pk)
        prescription.delete()
        return redirect('panel:prescriptions')


# Report Views

class ReportView(PanelView):
    def get(self, request, pk):
        is_valid = False
        try:
            report = Report.objects.get(id=pk)
            is_valid = True
        except Report.DoesNotExist:
            report = Report(doctor=None,
                            patient=None,
                            files=None,
                            dateCreated=None,
                            lastUpdated=None)
            is_valid = False  # Failsafe
        report.files = report.report_file_report.all()
        context = {'is_valid': is_valid, 'current_page': 'view_report', 'report': report}
        return render(request, 'report/report.html', context)


class ReportsView(PanelView):
    def get(self, request):
        reports = Report.objects.all()
        paginator = Paginator(reports, MODELS_PER_PAGE)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {'current_page': 'reports', 'reports': page_obj}
        return render(request, 'report/reports.html', context)


class AddReportView(PanelView):
    def get(self, request):
        form = ReportForm()
        form.fields['patient'].queryset = User.objects.filter(role=Roles.PATIENT.value)
        form.fields['doctor'].queryset = User.objects.filter(role=Roles.DOCTOR.value)
        context = {"current_page": "add_report", "form": form}
        return render(request, 'report/add_report.html', context)

    def post(self, request):
        form = ReportForm(request.POST, request.FILES)
        files = request.FILES.getlist('files')

        if form.is_valid():
            form.cleaned_data.pop('files')
            form.cleaned_data.pop('captcha')
            new_report = Report(**form.cleaned_data,
                                dateCreated=now,
                                lastUpdated=now)
            new_report.save()
            for f in files:
                file = ReportFile(file=f, report=new_report)
                file.save()
            return redirect('panel:reports')
        else:
            context = {"current_page": "add_report", "form": form}
            return render(request, "report/add_report.html", context)


class EditReportView(PanelView):
    def get(self, request, pk):
        report = Report.objects.get(id=pk)
        form = ReportForm(instance=report)
        form.fields['patient'].queryset = User.objects.filter(role=Roles.PATIENT.value)
        form.fields['doctor'].queryset = User.objects.filter(role=Roles.DOCTOR.value)
        context = {'current_page': 'edit_report', 'form': form}
        return render(request, 'report/add_report.html', context)

    def post(self, request, pk):

        try:
            report = Report.objects.get(id=pk)
        except Report.DoesNotExist:
            context = {'current_page': 'edit_report', 'form': ReportForm()}
            messages.error(request, "Report not found")
            return render(request, "report/add_report.html", context)

        form = ReportForm(request.POST, request.FILES, instance=report)
        files = request.FILES.getlist('files')

        if form.is_valid():
            form.cleaned_data.pop('files')
            form.cleaned_data.pop('captcha')
            report.lastUpdated = now
            report.save()

            for f in files:
                file = ReportFile(file=f, report=report)
                file.save()
            return redirect('panel:reports')
        else:
            context = {'current_page': 'edit_report', 'form': form}
            return render(request, "report/add_report.html", context)


class DeleteReportView(PanelView):
    def get(self, request, pk):
        context = {'current_page': 'delete_report'}
        return render(request, 'report/delete_report.html', context)

    def post(self, request, pk):
        if 'answer_no' in request.POST:
            return redirect('panel:report', pk=pk)

        report = Report.objects.get(id=pk)
        report.delete()
        return redirect('panel:reports')


# Product Views



class ProductView(PanelView):
    def get(self, request, pk):
        try:
            product = Product.objects.get(id=pk)
            is_valid = True
        except Product.DoesNotExist:
            product = None
            is_valid = False

        product.images = product.product_image_product.all()
        context = {'product': product, 'current_page': 'view_product', 'is_valid': is_valid}
        return render(request, 'product/product.html', context)


class ProductsView(PanelView):
    def get(self, request):

panel/templates/doctor/delete_doctor.html
{% extends 'panel/base/panel_base_index.html' %}

{% block title %}
<title>Delete Doctor - Clinicare</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="confirmation-card shadow">
            <form method="POST">
                {% csrf_token %}
                <h3>Are you sure?</h3>
                <p>Do you really want to delete this doctor?</p>
                <button type="submit" name="answer_yes" class="btn btn-primary">Yes</button>
                <button type="submit" name="answer_no" class="btn btn-secondary">No</button>
            </form>
        </div>
    </div>
{% endblock %}

panel/templates/doctor/doctor.html
{% extends 'panel/base/panel_base_index.html' %}

{% block title %}
<title>Doctor - Clinicare</title>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <nav class="mt-3" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'panel:dashboard' %}">Control Panel</a>
                <li class="breadcrumb-item"><a href="{% url 'panel:doctors' %}">Doctors</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ doctor.first_name }} {{ doctor.last_name }}</li>
            </ol>
        </nav>
        <div class="row">
            <div class="col-3">
                <div class="card photo-card">
                    <div class="card-img">
                        {% load static %}
                        <img class="img-fluid" src="{{ doctor.photo.url }}">
                    </div>
                </div>
                <div class="mt-5">
                    <a style="width: 19.5em" href="{% url 'panel:dr_add_appointment' pk=doctor.id %}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="Book an Appointment">
                        <i class="fa-solid fa-calendar-check ambitious-padding-btn"></i>
                        Book an Appointment
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="card" style="padding:1em">
                    {% if not is_valid %}
                        <h3 class="card-title" style="padding:0.5em">Doctor Not Found</h3>
                    {% endif %}
                        <div class="row">
                            <p class="col-sm-5">Name:</p>
                            <p class="col-sm-5">{{ doctor.first_name }}</p>
                        </div>
                        <div class="row">
                            <p class="col-sm-5">Surname:</p>
                            <p class="col-sm-5">{{ doctor.last_name }}</p>
                        </div>
                        <div class="row">
                            <p class="col-sm-5">Email:</p>
                            <p class="col-sm-5">{{ doctor.email }}</p>
                        </div>
                        <div class="row">
                            <p class="col-sm-5">Phone:</p>
                            <p class="col-sm-5">{{ doctor.phone }}</p>
                        </div>
                        <div class="row">
                            <p class="col-sm-5">Department:</p>
                            <p class="col-sm-5">{{ doctor.department }}</p>
                        </div>
                        <div class="row">
                            <p class="col-sm-5">Status:</p>
                            <p class="col-sm-5">{{ doctor.status }}</p>
                        </div>
                        <div class="row">
                            <p class="col-sm-5">Account Activated:</p>
                            <p class="col-sm-5">{{ doctor.is_active }}</p>
                        </div>
                        <div class="row">
                            <p class="col-sm-5">2FA Enabled:</p>
                            <p class="col-sm-5">{{ doctor.is2FAEnabled }}</p>
                        </div>
                        <div class="row">
                            <p class="col-sm-5">Last Login:</p>
                            <p class="col-sm-5">{{ doctor.lastLogin }}</p>
                        </div>
                        <div class="row">
                            <p class="col-sm-5">Account Created:</p>
                            <p class="col-sm-5">{{ doctor.dateCreated }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col" style="padding: 2em">
                <h3>Prescriptions</h3>
                <div class="card" style="padding: 1em">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Patient</th>
                                <th scope="col">Date</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for prescription in prescriptions %}
                            <tr>
                                <th scope="row">{{ prescription.id }}</th>
                                <td>{{ prescription.patient }}</td>
                                <td>{{ prescription.dateCreated }}</td>
                                <td>
                                    <a href="{% url 'panel:prescription' pk=prescription.id%}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="View">
                                        <i class="fa fa-eye ambitious-padding-btn"></i>
                                    </a>
                                    <a href="{% url 'panel:edit_prescription' pk=prescription.id %}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="Edit">
                                        <i class="fa fa-pencil ambitious-padding-btn"></i>
                                    </a>
                                    <a href="{% url 'panel:delete_prescription' pk=prescription.id %}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="Delete">
                                        <i class="fa fa-trash ambitious-padding-btn"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col" style="padding: 2em">
                <h3>Reports</h3>
                <div class="card" style="padding: 1em">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Patient</th>
                                <th scope="col">Report Type</th>
                                <th scope="col">Date</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for report in reports %}
                            <tr>
                                <th scope="row">{{ report.id }}</th>
                                <td>{{ report.patient }}</td>
                                <td>{{ report.type }}</td>
                                <td>{{ report.dateCreated }}</td>
                                <td>
                                    <a href="{% url 'panel:report' pk=report.id %}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="View">
                                        <i class="fa fa-eye ambitious-padding-btn"></i>
                                    </a>
                                    <a href="{% url 'panel:edit_report' pk=report.id %}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="Edit">
                                        <i class="fa fa-pencil ambitious-padding-btn"></i>
                                    </a>
                                    <a href="{% url 'panel:delete_report' pk=report.id %}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="Delete">
                                        <i class="fa fa-trash ambitious-padding-btn"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col" style="padding: 2em">
                <h3>Appointments</h3>
                <div class="card" style="padding: 1em">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Patient</th>
                                <th scope="col">Date</th>
                                <th scope="col">Created</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for appointment in appointments %}
                            <tr>
                                <th scope="row">{{ appointment.id }}</th>
                                <td>{{ appointment.patient }}
                                <td>{{ appointment.appointmentDate }}</td>
                                <td>{{ appointment.dateCreated }}</td>
                                <td>
                                    <a href="{% url 'panel:appointment' pk=appointment.id%}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="View">
                                        <i class="fa fa-eye ambitious-padding-btn"></i>
                                    </a>
                                    <a href="{% url 'panel:edit_appointment' pk=appointment.id %}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="Edit">
                                        <i class="fa fa-pencil ambitious-padding-btn"></i>
                                    </a>
                                    <a href="{% url 'panel:delete_appointment' pk=appointment.id %}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="Delete">
                                        <i class="fa fa-trash ambitious-padding-btn"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

panel/templates/doctor/doctors.html
{% extends 'panel/base/panel_base_index.html' %}

{% block title %}
<title>Doctors - Clinicare</title>
{% endblock %}

{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <section class="container-header">
                <h2>Doctors</h2>
            </section>
            <nav class="mt-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'panel:dashboard' %}">Control Panel</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Doctors</li>
                </ol>
            </nav>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Doctor List</h3>
                            <div class="card-tools">
                                <button class="btn btn-primary" data-toggle="collapse" href="#filter">
                                    <i class="fa fa-filter"></i> Filter
                                </button>
                            </div>
                        </div>
                        <div class="card-body">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Photo</th>
                                        <th scope="col">Name</th>
                                        <th scope="col">Email</th>
                                        <th scope="col">Phone</th>
                                        <th scope="col">Department</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for doctor in doctors %}
                                    <tr>
                                        <th scope="row">{{ doctor.id }}</th>
                                        <td><img class="img-fluid" style="max-height: 100px" src="{{ doctor.photo.url }}"></td>
                                        <td>{{ doctor }}</td>
                                        <td>{{ doctor.email }}</td>
                                        <td>{{ doctor.phone }}</td>
                                        <td>{{ doctor.department }}</td>
                                        <td>{{ doctor.status }}</td>
                                        <td>
                                            <a href="{% url 'panel:doctor' pk=doctor.id %}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="View">
                                                <i class="fa fa-eye ambitious-padding-btn"></i>
                                            </a>
                                            <a href="{% url 'panel:edit_doctor' pk=doctor.id %}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="Edit">
                                                <i class="fa fa-pencil ambitious-padding-btn"></i>
                                            </a>
                                            <a href="{% url 'panel:delete_doctor' pk=doctor.id %}" class="btn btn-info btn-outline btn-circle btn-lg" data-toggle="tooltip" title="Delete">
                                                <i class="fa fa-trash ambitious-padding-btn"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

              <ul class="pagination">
                {% if doctors.has_previous %}
                  <li class="page-item"><a class="page-link" ref="?page={{ doctors.previous_page_number }}">&laquo;</a></li>
                {% else %}
                  <li class="page-item disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in doctors.paginator.page_range %}
                  {% if doctors.number == i %}
                    <li class="page-item active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                  {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if doctors.has_next %}
                  <li class="page-item"><a class="page-link" href="?page={{ doctors.next_page_number }}">&raquo;</a></li>
                {% else %}
                  <li class="page-item disabled"><span>&raquo;</span></li>
                {% endif %}
              </ul>



        </div>
    </div>
{% endblock %}